---
abstract: 'PDL integration for ORLite'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: ORLite::PDL
name: ORLite-PDL
no_index:
  directory:
    - inc
    - t
requires:
  PDL: 2.004005
  PDL::Stats: 0.003002
  Params::Util: 1.00
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/ORLite-PDL
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/ORLite-PDL
version: 0.02
